---
title: "Mapas LISA"
author: "marcia"
date: "22/04/2020"
output: html_document
---


# Leitura Banco
```{r, echo=FALSE, message=FALSE, warning=FALSE}

library(ggplot2)
#############################################################pacotes da leitura do mapa
library(tidyverse)
library(sf)
library(stringr)
library(readxl)
library(leaflet)
library(RColorBrewer)


banco <- read_excel("dados_marcia_completo.xlsx", skip = 1)
banco_novo = banco %>% 
  gather(key = "aux", value = "valor", 3:50) %>%
  separate(col = aux, into = c("tipo", "ano"), sep = "_")  %>%
  spread(key= tipo, value = valor) %>%
  mutate(Cidade = str_to_lower(Cidade)) 

banco_novo$ano = as.numeric(banco_novo$ano)
banco_novo$prevalencia=10000*banco_novo$proporcao

banco_novo_tabela= subset(banco_novo, select = -proporcao )
banco_novo_tabela$Cidade=banco$Cidade
#################################################
################ banco de dados para a parte espacial
mapa_ma_shp <- sf::st_read("21.shp", quiet = TRUE)

dplyr::glimpse(mapa_ma_shp)
mapa_ma_shp <- mapa_ma_shp %>% 
  mutate(municipio = str_to_lower(NM_MUNICIP)) # todas as cidades com letra minuscula
# leituras dados luzivan

banco <- banco %>% 
  mutate(municipio = str_to_lower(Cidade)) # transforma as cidades em letra miniscula
banco$municipio = factor(banco$municipio)

banco_completo <- merge(banco, mapa_ma_shp, by.x = "municipio", by.y = "municipio") # une os dois bancos dado as cidades
dplyr::glimpse(banco_completo) # transforma em objeto espacial, n?o sei qual das duas funcoes usar
banco_completo = st_as_sf(banco_completo)
#transforma em um arquivo que o leaflet consegue ler!!!!
banco_completo_trasformado <- st_transform(banco_completo, "+init=epsg:4326")


#### Trocar os nomes de proporcao 2004 e proporcao 2005
names(banco_completo_trasformado)[15] = c("proporcao_2004")
names(banco_completo_trasformado)[18] = c("proporcao_2005")


```

# Índice I Moran

```{r, echo=FALSE, message=FALSE, warning=FALSE}

## I de Moran 

#install.packages("spdep")
library(spdep)


w <- poly2nb(banco_completo_trasformado$geometry, row.names=banco_completo_trasformado$municipio)
ww <-  nb2listw(w, style='B') #faz a matriz de pesos 0 ou 1


moran.mc(banco_completo_trasformado$proporcao_2001, ww, nsim=9999)
moran.mc(banco_completo_trasformado$proporcao_2002, ww, nsim=9999)
moran.mc(banco_completo_trasformado$proporcao_2003, ww, nsim=9999)
moran.mc(banco_completo_trasformado$proporcao_2004, ww, nsim=9999)
moran.mc(banco_completo_trasformado$proporcao_2005, ww, nsim=9999)
moran.mc(banco_completo_trasformado$proporcao_2006, ww, nsim=9999)
moran.mc(banco_completo_trasformado$proporcao_2007, ww, nsim=9999)
moran.mc(banco_completo_trasformado$proporcao_2008, ww, nsim=9999)
moran.mc(banco_completo_trasformado$proporcao_2009, ww, nsim=9999)
moran.mc(banco_completo_trasformado$proporcao_2010, ww, nsim=9999)
moran.mc(banco_completo_trasformado$proporcao_2011, ww, nsim=9999)
moran.mc(banco_completo_trasformado$proporcao_2012, ww, nsim=9999)
moran.mc(banco_completo_trasformado$proporcao_2013, ww, nsim=9999)
moran.mc(banco_completo_trasformado$proporcao_2014, ww, nsim=9999)
moran.mc(banco_completo_trasformado$proporcao_2015, ww, nsim=9999)
moran.mc(banco_completo_trasformado$proporcao_2016, ww, nsim=9999)



#moran.test(banco$PRESC_TOTAL/banco$pop_tot_cens_2010, ww, randomisation=FALSE)

#figura= moran.plot(banco$PRESC_TOTAL/banco$pop_tot_cens_2010, ww)




```


# Mapas LISA, considerando significância de 5\%

```{r, echo=FALSE, message=FALSE, warning=FALSE}
 library(leaflet)
 library(htmlwidgets)
 library(htmltools)

locm <- localmoran(banco_completo_trasformado$proporcao_2001, ww)
banco_completo_trasformado$Sgini <- scale(banco_completo_trasformado$proporcao_2001)
banco_completo_trasformado$lag <- lag.listw(ww, banco_completo_trasformado$Sgini)
banco_completo_trasformado$pval <- locm[, 5]

#Making a LISA Map
banco_completo_trasformado$quad_sig <- ifelse(banco_completo_trasformado$Sgini >= 0 & banco_completo_trasformado$lag >= 0 & banco_completo_trasformado$pval <= 0.05, 1,
                      ifelse(banco_completo_trasformado$Sgini <= 0 & banco_completo_trasformado$lag <= 0 & banco_completo_trasformado$pval <= 0.05, 2,
                      ifelse(banco_completo_trasformado$Sgini >= 0 & banco_completo_trasformado$lag <= 0 & banco_completo_trasformado$pval <= 0.05, 3,
                      ifelse(banco_completo_trasformado$Sgini >= 0 & banco_completo_trasformado$lag <= 0 & banco_completo_trasformado$pval <= 0.05, 4, 5))))

breaks <- seq(1, 5, 1)
labels <- c("High-High", "Low-Low", "High-Low", "Low-High", "Not Signif.")
np <- findInterval(banco_completo_trasformado$quad_sig, breaks)
colors <- c("red", "blue", "lightpink", "skyblue2", "white")
#Making a LISA Map
#plot(banco_completo_trasformado, col = colors[np])
#mtext("Local Moran's I\nof Gini Index", cex = 1.5, side = 3, line = 1)
#legend("topright", legend = labels, fill = colors, bty = "n")
#plot of chunk unnamed-chunk-12


banco_completo_trasformado$quad_sig <- ifelse(banco_completo_trasformado$Sgini >= 0 & banco_completo_trasformado$lag >= 0 & banco_completo_trasformado$pval <= 0.05, 1,
                      ifelse(banco_completo_trasformado$Sgini <= 0 & banco_completo_trasformado$lag <= 0 & banco_completo_trasformado$pval <= 0.05, 2,
                      ifelse(banco_completo_trasformado$Sgini >= 0 & banco_completo_trasformado$lag <= 0 & banco_completo_trasformado$pval <= 0.05, 3,
                      ifelse(banco_completo_trasformado$Sgini >= 0 & banco_completo_trasformado$lag <= 0 & banco_completo_trasformado$pval <= 0.05, 4, 5))))

#breaks <- seq(1, 5, 1)
#labels <- c("High-High", "Low-Low", "High-Low", "Low-High", "Not Signif.")
#np <- findInterval(banco_completo_trasformado$quad_sig, breaks)
#colors <- c("red", "blue", "lightpink", "skyblue2", "white")

#plot(sa, col = colors[np])
#mtext("Local Moran's I\nof Gini Index", cex = 1.5, side = 3, line = 1)
#legend("topright", legend = labels, fill = colors, bty = "n")


banco_completo_trasformado$quad_sig <- factor(banco_completo_trasformado$quad_sig,
levels = c(1,2,3, 4, 5),
labels = c("Alto-Alto", "Baixo-Baixo", "Alto-Baixo", "Baixo-Alto", "Não Significativo"))    
    
pal <- colorFactor(palette = c("red", "blue", "green", "green", "gray"), domain = banco_completo_trasformado$quad_sig)
y=banco_completo_trasformado$quad_sig


### funcao para colocar o titulo no meio do grafico https://stackoverflow.com/questions/49072510/r-add-title-to-leaflet-map
tag.map.title <- tags$style(HTML("   
  .leaflet-control.map-title { 
    transform: translate(-50%,20%);
    position: fixed !important;
    #left: 50%;
    left: 30%;
    text-align: center;
    padding-left: 10px; 
    padding-right: 10px; 
    background: rgba(255,255,255,0.75);
    font-weight: bold;
    font-size: 28px;
  }
"))


    
mapa_2001 = leaflet(banco_completo_trasformado) %>%
      addProviderTiles(providers$OpenStreetMap.Mapnik) %>%
      addPolygons(fillColor = ~pal(y), 
                  weight = 1.5,
                  opacity = 1,
                  fillOpacity = 0.7,
                  color = "gray",
                  highlight = highlightOptions(
                    weight = 5,
                    color = "#666",
                    fillOpacity = 0.7,
                    bringToFront = TRUE),
                  label = sprintf("%s - %s", banco_completo_trasformado$Cidade, y),
                  labelOptions = labelOptions(
                    style = list("font-weight" = "normal", padding = "6px 11px"),
                    textsize = "15px",
                    direction = "auto")) %>%
      addLegend(pal = pal, values = ~y, opacity = 0.7, title = NULL,
                labFormat = labelFormat(digits = 5),
                position = "bottomright")%>%
  addScaleBar(position = 'bottomleft') %>%
    addTiles() %>%
   addControl( tags$div(tag.map.title, HTML("2001")), position = "topleft", className="map-title") ## aqui dá pra mudar o titulo 

```


```{r, echo=FALSE, message=FALSE, warning=FALSE}

# library(magrittr)
# #install.packages("leafsync")
# library(leafsync)
# 
# leafsync::latticeview(mapa_ostomuscular, mapa_sistema_nervoso)
# 
# leafsync::latticeview(mapa_ostomuscular, mapa_sistema_nervoso, ncol = 2, sync = list(c(1, 2)), sync.cursor = TRUE, no.initial.sync = FALSE)

```


